defaults:
  - _self_
  - env_cfg@_global_: ph

seed: 0

model_path: ""

batch_size: 512

reward_scale: 1.0
reward_bias: 0.0
clip_action: 0.99999

render_num: 1

n_train_step_per_epoch_offline: 1000
n_pretrain_epochs: 0 # 500
offline_eval_every_n_epoch: 10 # 50

max_online_env_steps: 500000 # 0
online_eval_every_n_env_steps: 2000

eval_n_trajs: 10 # default 5
replay_buffer_size: 1000000
mixing_ratio: 0.5 # default -1.0

n_online_traj_per_epoch: 1
online_utd_ratio: 1

discount: 0.99
demo_percentile: 0
demo_ratio: 100.0
demo_only: false
demo_relabel: false

alg:
  name: sqar
  discount: ${discount}

  qf_lr: 0.0003
  vf_lr: ${alg.qf_lr}
  optimizer_type: adam
  soft_target_update_rate: 0.005
  cql_temp: 1.0

  qchunk_size: -1
  use_nbias: false
  abl_skip: -1

  soft_alpha: 0.1
  act_alpha: ${alg.soft_alpha}
  levels: 1
  bins: 41

  # update
  act_network: "default" # default, target

  # bellman-q
  bellman_loss_coef: 1.0

  # bellman-cql
  cql_type: "cql" # cql, margin
  cql_min_q_weight: 5.0
  cql_clip_diff_min: -1 # -10000000
  cql_clip_diff_max: 10000000

wandb:
  project: arsq_d4rl
  name: "arsq"

hydra:
  run:
    dir: ./arsq_d4rl/exp_local/arsq/${env}/${now:%Y}_${now:%m%d}_${now:%H%M}_${now:%S}
